server.port=8092
spring.application.name=b3-investment-registry
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
spring.main.banner-mode=off
logging.level.root=INFO
logging.level.com.dogbank.registry=INFO
