server.port=8091

spring.application.name=investment-module

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true

investment.cdi.annual-rate=0.1065
investment.cdi.daily-rate=0.00042262
investment.btc.price-brl=342500.00
investment.drift.threshold-percent=0.50

logging.level.root=INFO
logging.level.com.dogbank=INFO
logging.config=classpath:log4j2.xml
spring.main.banner-mode=off
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
