server {
    listen 80;
    listen 443 ssl;
    server_name localhost lab.dogbank.dog;

    ssl_certificate /etc/nginx/certs/lab.dogbank.dog.pem;
    ssl_certificate_key /etc/nginx/certs/lab.dogbank.dog-key.pem;
  root /usr/share/nginx/html;

  location / { try_files $uri /index.html; }
  location = /health {
    access_log off;
    add_header Content-Type text/plain;
    return 200 "ok\n";
  }
}
