-- =============================================================================
-- 05-demo-clients-br.sql  — GENERATED by gen-demo-clients.py (do not edit by hand)
-- Synthetic Brazilian clients for the EBC SQL-injection --dump demo.
-- CPFs have valid check digits but are fabricated (not real people).
-- Runs after 01-init.sql; adds clients + matching contas for the UNION SQLi.
-- =============================================================================

INSERT INTO usuarios (cpf, senha, nome, email, chave_pix) VALUES
('50709961006', '123456', 'William Santos', 'william.santos54@gmail.com', 'william.santos54@gmail.com'),
('40537478809', '123456', 'Leonardo Alves', 'leonardo.alves1@hotmail.com', 'leonardo.alves1@hotmail.com'),
('62961961300', '123456', 'Thiago Santos', 'thiago.santos86@uol.com.br', '50049655-5880-pix'),
('34422516647', '123456', 'William Dias', 'william.dias32@hotmail.com', 'william.dias32@hotmail.com'),
('46233347165', '123456', 'William Barbosa', 'william.barbosa57@uol.com.br', 'william.barbosa57@uol.com.br'),
('71674242182', '123456', 'Nicolas Ribeiro', 'nicolas.ribeiro84@outlook.com', '58002371-4582-pix'),
('81723106763', '123456', 'Isabela Alves', 'isabela.alves15@yahoo.com.br', '+5511950863128'),
('42052790861', '123456', 'Vanessa Cardoso', 'vanessa.cardoso92@hotmail.com', '70469358-5909-pix'),
('07174658962', '123456', 'Caio Santos', 'caio.santos81@gmail.com', '29572897-9938-pix'),
('49316659264', '123456', 'Larissa Ribeiro', 'larissa.ribeiro82@hotmail.com', '+5511976054422'),
('33854380399', '123456', 'Nicolas Barbosa', 'nicolas.barbosa42@uol.com.br', '+5511994242523'),
('49650462260', '123456', 'Marcela Carvalho', 'marcela.carvalho4@outlook.com', '72778427-8844-pix'),
('58515168871', '123456', 'Leonardo Fernandes', 'leonardo.fernandes28@gmail.com', '29207258-9227-pix'),
('36838854244', '123456', 'Karina Cardoso', 'karina.cardoso81@outlook.com', 'karina.cardoso81@outlook.com'),
('14059258920', '123456', 'Eduarda Gomes', 'eduarda.gomes71@uol.com.br', '50998750-2872-pix'),
('23152252803', '123456', 'Henrique Rocha', 'henrique.rocha51@hotmail.com', 'henrique.rocha51@hotmail.com'),
('06559362701', '123456', 'Juliana Santos', 'juliana.santos77@gmail.com', '+5511940554996'),
('36970234037', '123456', 'Bruno Souza', 'bruno.souza53@outlook.com', '77160496-1539-pix'),
('74155891573', '123456', 'Mariana Lopes', 'mariana.lopes46@hotmail.com', 'mariana.lopes46@hotmail.com'),
('62119869804', '123456', 'Rodrigo Lopes', 'rodrigo.lopes43@outlook.com', '42915734-9815-pix'),
('13054070670', '123456', 'Patrícia Barbosa', 'patricia.barbosa97@uol.com.br', 'patricia.barbosa97@uol.com.br'),
('65836453519', '123456', 'João Ferreira', 'joao.ferreira15@yahoo.com.br', 'joao.ferreira15@yahoo.com.br'),
('84421595683', '123456', 'Mariana Dias', 'mariana.dias23@outlook.com', '27008114-7948-pix'),
('75021402048', '123456', 'Sabrina Souza', 'sabrina.souza10@gmail.com', 'sabrina.souza10@gmail.com'),
('41857268059', '123456', 'João Moreira', 'joao.moreira32@outlook.com', '+5511989626500'),
('36458633700', '123456', 'Gustavo Rodrigues', 'gustavo.rodrigues61@yahoo.com.br', 'gustavo.rodrigues61@yahoo.com.br'),
('06624138734', '123456', 'Nicolas Moreira', 'nicolas.moreira66@outlook.com', 'nicolas.moreira66@outlook.com'),
('38786782665', '123456', 'Eduarda Araújo', 'eduarda.araujo93@gmail.com', '15585206-1816-pix'),
('77862242203', '123456', 'Sabrina Araújo', 'sabrina.araujo53@gmail.com', '+5511975115715'),
('64215759196', '123456', 'Mariana Ferreira', 'mariana.ferreira52@hotmail.com', '38791544-2815-pix'),
('40260465917', '123456', 'Felipe Dias', 'felipe.dias66@gmail.com', '22958222-5138-pix'),
('16526440592', '123456', 'Camila Barbosa', 'camila.barbosa71@uol.com.br', 'camila.barbosa71@uol.com.br'),
('50767826752', '123456', 'Marcela Alves', 'marcela.alves21@outlook.com', '+5511994991875'),
('75600096461', '123456', 'Yasmin Nascimento', 'yasmin.nascimento41@outlook.com', '+5511992907904'),
('40260519510', '123456', 'Vanessa Dias', 'vanessa.dias9@yahoo.com.br', '+5511948167920'),
('73623278033', '123456', 'Thiago Barbosa', 'thiago.barbosa29@hotmail.com', '+5511962505571')
ON CONFLICT (cpf) DO NOTHING;

INSERT INTO contas (usuario_id, numero_conta, saldo, banco, user_name)
SELECT u.id, v.numero_conta, v.saldo, v.banco, v.user_name
FROM (VALUES
  ('50709961006', '9678-9', 2050.83, 'PicPay', 'William Santos'),
  ('40537478809', '6604-6', 376.90, 'PicPay', 'Leonardo Alves'),
  ('62961961300', '8064-1', 24932.17, 'C6 Bank', 'Thiago Santos'),
  ('34422516647', '4863-2', 13878.52, 'Banco do Brasil', 'William Dias'),
  ('46233347165', '3738-4', 18773.81, 'Bradesco', 'William Barbosa'),
  ('71674242182', '8376-2', 19896.43, 'Banco do Brasil', 'Nicolas Ribeiro'),
  ('81723106763', '4885-2', 9451.16, 'C6 Bank', 'Isabela Alves'),
  ('42052790861', '1118-6', 27227.20, 'Banco Inter', 'Vanessa Cardoso'),
  ('07174658962', '8434-1', 20828.20, 'Caixa', 'Caio Santos'),
  ('49316659264', '8223-2', 10715.35, 'Itau', 'Larissa Ribeiro'),
  ('33854380399', '7693-2', 27408.29, 'Banco do Brasil', 'Nicolas Barbosa'),
  ('49650462260', '7038-8', 25784.05, 'Santander', 'Marcela Carvalho'),
  ('58515168871', '6972-1', 21697.78, 'Banco do Brasil', 'Leonardo Fernandes'),
  ('36838854244', '7352-1', 871482.51, 'Caixa', 'Karina Cardoso'),
  ('14059258920', '9443-2', 17982.42, 'PicPay', 'Eduarda Gomes'),
  ('23152252803', '2421-8', 33271.38, 'PicPay', 'Henrique Rocha'),
  ('06559362701', '7938-2', 32264.12, 'Nubank', 'Juliana Santos'),
  ('36970234037', '2935-3', 741348.50, 'Banco Inter', 'Bruno Souza'),
  ('74155891573', '7031-0', 4686.85, 'Neon', 'Mariana Lopes'),
  ('62119869804', '2735-2', 628606.51, 'PicPay', 'Rodrigo Lopes'),
  ('13054070670', '8435-8', 480085.34, 'PicPay', 'Patrícia Barbosa'),
  ('65836453519', '1625-6', 8282.14, 'DOG BANK', 'João Ferreira'),
  ('84421595683', '3138-3', 24969.21, 'Nubank', 'Mariana Dias'),
  ('75021402048', '5232-2', 428654.30, 'Itau', 'Sabrina Souza'),
  ('41857268059', '5739-0', 32957.54, 'PicPay', 'João Moreira'),
  ('36458633700', '9677-8', 14343.90, 'Nubank', 'Gustavo Rodrigues'),
  ('06624138734', '3435-5', 11088.86, 'Santander', 'Nicolas Moreira'),
  ('38786782665', '8181-7', 37575.56, 'DOG BANK', 'Eduarda Araújo'),
  ('77862242203', '4597-2', 7510.64, 'Itau', 'Sabrina Araújo'),
  ('64215759196', '8492-2', 39718.74, 'Banco do Brasil', 'Mariana Ferreira'),
  ('40260465917', '2287-9', 528636.27, 'Neon', 'Felipe Dias'),
  ('16526440592', '9934-8', 16307.37, 'Santander', 'Camila Barbosa'),
  ('50767826752', '5111-8', 1192.12, 'Banco Inter', 'Marcela Alves'),
  ('75600096461', '5627-9', 11769.00, 'Neon', 'Yasmin Nascimento'),
  ('40260519510', '4572-9', 2165.03, 'Bradesco', 'Vanessa Dias'),
  ('73623278033', '1444-2', 843158.30, 'Banco Inter', 'Thiago Barbosa')
) AS v(cpf, numero_conta, saldo, banco, user_name)
JOIN usuarios u ON u.cpf = v.cpf
ON CONFLICT (numero_conta) DO NOTHING;

DO $$ BEGIN
  RAISE NOTICE '✅ Demo BR clients carregados: 36 clientes (7 contas >= R$ 50k / COAF)';
END $$;
