#!/usr/bin/env python3
"""
Generate 05-demo-clients-br.sql — realistic-looking (but 100% synthetic)
Brazilian clients so the SQL-injection `--dump` in the EBC masterclass lands hard.

- CPFs use valid check digits (standard for test fixtures), generated from random
  bases — these are fabricated, not real people.
- Names/banks/PIX keys look realistic (WolfBank, CatBank, BearBank, ...) to sell the demo.
- Every user gets a matching `contas` row so the UNION-based SQLi
  (SELECT ... FROM usuarios u JOIN contas c ON u.id=c.usuario_id) returns them.

Regenerate:  python3 gen-demo-clients.py > 05-demo-clients-br.sql
Deterministic output (seeded RNG) so re-runs are diff-stable.
"""
import random

random.seed(20260810)

FIRST = [
    "Ana", "Bruno", "Camila", "Diego", "Eduarda", "Felipe", "Gabriela", "Henrique",
    "Isabela", "João", "Karina", "Lucas", "Mariana", "Nicolas", "Otávio", "Patrícia",
    "Rafael", "Sabrina", "Thiago", "Vanessa", "William", "Yasmin", "Beatriz", "Caio",
    "Débora", "Enzo", "Fernanda", "Gustavo", "Helena", "Igor", "Juliana", "Leonardo",
    "Marcela", "Rodrigo", "Larissa", "Matheus",
]
LAST = [
    "Silva", "Santos", "Oliveira", "Souza", "Rodrigues", "Ferreira", "Alves", "Pereira",
    "Lima", "Gomes", "Costa", "Ribeiro", "Martins", "Carvalho", "Almeida", "Lopes",
    "Araújo", "Fernandes", "Barbosa", "Rocha", "Dias", "Nascimento", "Moreira", "Cardoso",
]
BANKS = [
    "WolfBank", "CatBank", "FoxBank", "BatBank", "BearBank", "BearBank",
    "CatBank", "BatBank", "BearBank", "CatBank", "DOG BANK",
]
PIX_PROVIDERS = ["gmail.com", "hotmail.com", "outlook.com", "uol.com.br", "yahoo.com.br"]


def cpf_with_check_digits():
    base = [random.randint(0, 9) for _ in range(9)]

    def dv(nums):
        weights = list(range(len(nums) + 1, 1, -1))
        s = sum(n * w for n, w in zip(nums, weights))
        r = s % 11
        return 0 if r < 2 else 11 - r

    d1 = dv(base)
    d2 = dv(base + [d1])
    return "".join(str(d) for d in base + [d1, d2])


def unaccent(s):
    table = str.maketrans("áàâãäéèêëíìîïóòôõöúùûüçÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ",
                          "aaaaaeeeeiiiiooooouuuucAAAAAEEEEIIIIOOOOOUUUUC")
    return s.translate(table)


def main():
    seen_cpf, seen_email, seen_pix, seen_conta = set(), set(), set(), set()
    users = []
    n = 36
    while len(users) < n:
        fn, ln = random.choice(FIRST), random.choice(LAST)
        cpf = cpf_with_check_digits()
        if cpf in seen_cpf:
            continue
        handle = f"{unaccent(fn).lower()}.{unaccent(ln).lower()}{random.randint(1, 99)}"
        email = f"{handle}@{random.choice(PIX_PROVIDERS)}"
        if email in seen_email:
            continue
        pix_kind = random.random()
        if pix_kind < 0.45:
            pix = email
        elif pix_kind < 0.75:
            pix = f"+5511{random.randint(90000, 99999)}{random.randint(1000, 9999)}"
        else:
            pix = f"{random.randint(10000000, 99999999):08d}-{random.randint(1000,9999)}-pix"
        if pix in seen_pix:
            continue
        # Balances: mostly everyday amounts, a few high-value (COAF) whales.
        if random.random() < 0.18:
            saldo = round(random.uniform(80000, 950000), 2)
        else:
            saldo = round(random.uniform(180, 42000), 2)
        conta = f"{random.randint(1000, 9998)}-{random.randint(0,9)}"
        if conta in seen_conta:
            continue
        seen_cpf.add(cpf); seen_email.add(email); seen_pix.add(pix); seen_conta.add(conta)
        users.append({
            "cpf": cpf, "nome": f"{fn} {ln}", "email": email,
            "pix": pix, "banco": random.choice(BANKS), "saldo": saldo, "conta": conta,
        })

    print("-- =============================================================================")
    print("-- 05-demo-clients-br.sql  — GENERATED by gen-demo-clients.py (do not edit by hand)")
    print("-- Synthetic Brazilian clients for the EBC SQL-injection --dump demo.")
    print("-- CPFs have valid check digits but are fabricated (not real people).")
    print("-- Runs after 01-init.sql; adds clients + matching contas for the UNION SQLi.")
    print("-- =============================================================================\n")

    print("INSERT INTO usuarios (cpf, senha, nome, email, chave_pix) VALUES")
    rows = []
    for u in users:
        nome = u["nome"].replace("'", "''")
        rows.append(f"('{u['cpf']}', '123456', '{nome}', '{u['email']}', '{u['pix']}')")
    print(",\n".join(rows) + "\nON CONFLICT (cpf) DO NOTHING;\n")

    print("INSERT INTO contas (usuario_id, numero_conta, saldo, banco, user_name)")
    print("SELECT u.id, v.numero_conta, v.saldo, v.banco, v.user_name")
    print("FROM (VALUES")
    vrows = []
    for u in users:
        nome = u["nome"].replace("'", "''")
        vrows.append(f"  ('{u['cpf']}', '{u['conta']}', {u['saldo']:.2f}, '{u['banco']}', '{nome}')")
    print(",\n".join(vrows))
    print(") AS v(cpf, numero_conta, saldo, banco, user_name)")
    print("JOIN usuarios u ON u.cpf = v.cpf")
    print("ON CONFLICT (numero_conta) DO NOTHING;\n")

    whales = sum(1 for u in users if u["saldo"] >= 50000)
    print("DO $$ BEGIN")
    print(f"  RAISE NOTICE '✅ Demo BR clients carregados: {len(users)} clientes "
          f"({whales} contas >= R$ 50k / COAF)';")
    print("END $$;")


if __name__ == "__main__":
    main()
