services:
  kali:
    image: localhost/dogbank-kali:latest
    container_name: kali
    hostname: kali-attacker
    stdin_open: true
    tty: true
    privileged: true
    environment:
      - TARGET=lab.dogbank.dog
    networks:
      - dogbank-network
    ports:
      - "6080:8080"
      - "5900:5900"

networks:
  dogbank-network:
    external: true
    name: dogbank_dogbank-network
